services:
  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    environment:
      - API_KEY=A
    deploy:
      replicas: 1
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:80"
    volumes:
      - ./frontend/public:/app/public
