version: "3.9"
services:
  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    environment:
      - API_KEY=e610b76919aa41d29c5215108242611
    deploy:
      replicas: 1
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:80"
